### ISSUE TITLE
Switch from magvar to geomag

### ISSUE THREAD

**Issue by wtip** [bahaidev/qiblih-website#11]
Let's switch over to https://github.com/janrg/wmm-geomagnetic

@janrg noticed an issue https://github.com/dpyeates/magvar/pull/3 and fixed it in his fork

**Comment by brettz9** [comment]
I've started some work on a tool I hope to apply in a PR to this project which aims to check one's source and current npm dependencies for external script/stylesheet version and integrity info, so that when one updates dependencies (e.g., using the useful npm packages `updates` or `npm-check-updates`), one can safely auto-update the integrity SHAs and versioned URLs accordingly (without needing to consult the respective hosting source websites for checksums or manually editing the version numbers in the URLs).

I hope to apply that to that my PR for this project at the same time as adding Rollup (and @janrg's fork has the additional benefit of our not needing to add the Rollup CommonJS plugin).

**Comment by janrg** [comment]
Renamed the package from wmm-geomagnetic to geomag

**Comment by wtip** [comment]
@brettz9 How are your changes coming along? I'm wondering if I should apply an update to magvar in the meantime to get the issue fixed.

**Comment by brettz9** [comment]
Hi, @wtip . It's coming along--I have the project published now on npm and at https://github.com/brettz9/integrity-matters . However, I still want to add some features that I think may be of assistance to this project, e.g., to allow HTML data attributes and/or config which suggest a particular CDN to use for a particular package.

Though I intend to keep working on it, given that it may still take a little time, and I cannot, for health reasons, be very reliable in general in carrying through in a predictably timely manner, you may want to go ahead and update.

Note, however, if you go ahead, you'll need to make some API changes, e.g.:

```js
  const magVar = Magvar.get(B.getLatLng().lat, B.getLatLng().lng);
  info.update(geodesic.statistics, magBearing(vector.initialBearing.toFixed(0), magVar));
```

to

```js
  const {declination} = Geomag.field(B.getLatLng().lat, B.getLatLng().lng);
  info.update(geodesic.statistics, magBearing(vector.initialBearing.toFixed(0), declination));
```

**Comment by brettz9** [comment]
Filed #12 which should resolve this.
